{"content": {"suites": {"0": {"status": {"total_pass": 0, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 9, "total_error": 0}, "tests": {"0": {"status": "FAIL", "message": "               ValueError: 0 is not in range\n               KeyError: 0\n", "test_name": "test_kicking[a021820220]", "rerun": "0"}, "1": {"status": "FAIL", "message": "               ValueError: 0 is not in range\n               KeyError: 0\n", "test_name": "test_kicking[a021820221]", "rerun": "0"}, "2": {"status": "FAIL", "message": "               ValueError: 0 is not in range\n               KeyError: 0\n", "test_name": "test_kicking[a123452015ngel0]", "rerun": "0"}, "3": {"status": "FAIL", "message": "               ValueError: 0 is not in range\n               KeyError: 0\n", "test_name": "test_kicking[a123452015ngel1]", "rerun": "0"}, "4": {"status": "FAIL", "message": "               ValueError: 0 is not in range\n               KeyError: 0\n", "test_name": "test_kicking[a1234560]", "rerun": "0"}, "5": {"status": "FAIL", "message": "               ValueError: 0 is not in range\n               KeyError: 0\n", "test_name": "test_kicking[a1234561]", "rerun": "0"}, "6": {"status": "FAIL", "message": "               ValueError: 0 is not in range\n               KeyError: 0\n", "test_name": "test_kicking[aaireeen60]", "rerun": "0"}, "7": {"status": "FAIL", "message": "               ValueError: 0 is not in range\n               KeyError: 0\n", "test_name": "test_kicking[aaireeen61]", "rerun": "0"}, "8": {"status": "FAIL", "message": "               ValueError: 0 is not in range\n               KeyError: 0\n", "test_name": "test_kicking[abel760]", "rerun": "0"}}, "suite_name": "test_halo_game.py"}}}, "date": "October 12, 2022", "start_time": 1665553867.986472, "total_suite": 1, "status": "FAIL", "status_list": {"pass": "0", "fail": "9", "skip": "0", "error": "0", "xpass": "0", "xfail": "0", "rerun": "0"}, "total_tests": "9"}